### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by xeffyr** [xeffyr-archived/.github#1]

**Comment by thunder-coding** [comment]
Hey there @raknirre, I would like to confirm whether it's really Leonid Pliushch out there or someone else trying to be an imposter. Can you please mail both Grimler and Agnostic Apollo (not pinging them here intentionally) to confirm whether it's really you. I'll only consider you as legitimate xeffyr when they confirm the same.

**Comment by MedzikUser** [comment]
> Hey there @raknirre, I would like to confirm whether it's really Leonid Pliushch out there or someone else trying to be an imposter. Can you please mail both Grimler and Agnostic Apollo (not pinging them here intentionally) to confirm whether it's really you (preferably signed with your GPG keys). I'll only consider you as legitimate xeffyr when they confirm the same.

![img](https://cdn.magicuser.cf/ZaSOA7G.png)

I think he's using his own email but it's better to verify it

**Comment by agnostic-apollo** [comment]
He already emailed from his account and a forwarded a past email.
